# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: metacodesolution
# "service" is the name of this project. This will also be added to your AWS resource names.
service: adilaxmi-serverless-api

provider:
  name: aws
  runtime: python3.12

functions:
  adlAuthorizer:
    handler: handler.adl_authorizer.adlAuthorizer
    layers:
      - arn:aws:lambda:eu-north-1:975050131916:layer:aws-fis-extension-x86_64:68
    events:
      - httpApi:
          path: /api/auth
          method: post
  changeLanguage:
    handler: handler.change_language.changeLanguage
    layers:
      - arn:aws:lambda:eu-north-1:975050131916:layer:aws-fis-extension-x86_64:68
    events:
      - httpApi:
          path: /api/changelanguage
          method: post


layers:
  python-app-dependencies:
    path: layers/tools
    compatibleRuntimes:
      - python3.12
    description: "Dependencies Lambda Functions"